function Q = getinformfiles(fname)
%
Markers.Opals = [520,540,570,620,650,690];
Markers.all = {'PDL1','CD8','FoxP3','Tumor','PD1','CD163'};
%
warning('off','MATLAB:table:ModifiedAndSavedVarnames')
%
% create format specifier for each column in the table
%
formatspec = strcat(repmat('%s ',[1,4]),{' '},repmat('%d16 ',[1,11]),...
    { ' %s '},repmat('%f64 ',[1,45]),{' %s '},repmat('%f64 ',[1,45]),...
    {' %s '},repmat('%f64 ',[1,45]),{' %s '},repmat('%f64 ',[1,44]),...
    {' '},repmat('%s ',[1,2]),{' '}, repmat('%f64 ',[1,4]),{' '}, ....
    repmat('%s ',[1,2]));
formatspec = formatspec{1};
%
T = readtable(fname,'Format',formatspec,...
    'Delimiter','\t','TreatAsEmpty',{' ','#N/A'});
%
vars.Opals = Markers.Opals;
vars.names = cell(1,length(Markers.all)*8);
vars.type = [repmat({'Mean'},1,4), repmat({'Total'},1,4)];
vars.comp = repmat({'Nucleus', 'Membrane','EntireCell','Cytoplasm'},1,2);
%
% create DAPI column names
%
a(:,1)= cellfun(@(x,y)strcat(x,'DAPI','_DAPI_',...
    y,'_NormalizedCounts_TotalWeighting_'),vars.comp,vars.type,'Uni',0);
b(:,1)= cellfun(@(x,y)strcat(y,x,'DAPI'),vars.comp,vars.type,'Uni',0);
%
% column names for all other markers
%
for i3 = 1:length(vars.Opals)
    a(:,i3+1) = cellfun(@(x,y)strcat(...
        x,Markers.all{i3},'_Opal',num2str(vars.Opals(i3)),'_',y,...
        '_NormalizedCounts_TotalWeighting_'),vars.comp,vars.type,'Uni',0);
    %
    b(:,i3+1) = cellfun(@(x,y)strcat(y,x,num2str(vars.Opals(i3))),...
        vars.comp,vars.type,'Uni',0);
end
%
% put the strings into a single vector
%
vars.namesin = horzcat(a(1,:),a(2,:),a(3,:),a(4,:),a(5,:),a(6,:),a(7,:),a(8,:));
vars.names = horzcat(b(1,:),b(2,:),b(3,:),b(4,:),b(5,:),b(6,:),b(7,:),b(8,:));
%
Q = T(:,[{'SampleName','SlideID',...
    'CellID','Phenotype','CellXPosition',...
    'CellYPosition','EntireCellArea_pixels_','NucleusArea_pixels_'},...
    {'MembraneArea_pixels_','CytoplasmArea_pixels_'},...
    vars.namesin{:},'Confidence']);
Q.Properties.VariableNames = ...
    [{'SampleName','SlideID',...
    'CellID','Phenotype','CellXPos',...
    'CellYPos','EntireCellArea','NucleusArea',...
    'MembraneArea','CytoplasmArea'},...
    vars.names{:},'Confidence'];
end